import Head from 'next/head'
import styled from '@emotion/styled'
import { auth } from '../firebase';
import Sidebar from '../components/Sidebar'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Digital Twins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Sidebar/>
      </Container>
    </div>
  )
}

const Container = styled.div`
display:flex;
flex-direction:row;
height: 100%;
width: 100%;
background-image: url('/bg1.jpg');
`;